package com.onelogin.mfa.data.encryption

/**
 * Takes a string and encrypts its content, returning an encrypted version of the string
 */
interface EncryptionManager{

    /**
     * Takes some plain data and returns an encrypted and version of the data
     * @param plainData Data to be encrypted
     * @return Encrypted representation of `plainData`
     */
    fun encrypt(plainData: String): String

    /**
     * Takes an encrypted representation generated by `encrypt()` and returns the decrypted information
     * @return Decrypted information based on `encryptedData`
     */
    fun decrypt(encryptedData: String): String

    /**
     * Checks whether or not encryption is supported on the device
     * @return True if encryption is supported, else false
     */
    fun isSupported(): Boolean
}
