name: git-secrets

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:        
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: source

      - name: Fetch IKE Bot PAT from AWS SM
        uses: say8425/aws-secrets-manager-actions@v2
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
          SECRET_NAME: "ci/gh-actions/ike-bot-pat/repositories-rw"

      - name: Checkout OneLogin Actions
        uses: actions/checkout@v2
        with:
          repository: onelogin/.github-private
          token: ${{ env.IKE_BOT_PAT }}
          path: onelogin-actions

      - uses: ./onelogin-actions/security/actions/git-secrets-install/v1
      - uses: ./onelogin-actions/security/actions/git-secrets-scan/v1
